[package]
name = "rvst"
version = "0.2.5"
authors = ["Emilian Stankov <eminstine@gmail.com>"]

[dependencies]
vst = { git = "https://github.com/rust-dsp/rust-vst" }
rand = "0.4.2"

[lib]
crate-type = ["dylib"]
